from django.utils.translation import gettext_lazy as _
from weblate.checks.base import TargetCheck


class LineLength(TargetCheck):

    # Used as identifier for check, should be unique
    # Has to be shorter than 50 characters
    check_id = "LineLength"

    # Short name used to display failing check
    name = _("Line Length")

    # Description for failing check
    description = _("Line length check has failed. Each line must be <= 46 characters.")

    # Real check code
    # Return True if you want check to fail on match
    # Weblate assigns strings as unicode, so we need to encode first

    def replace_with_placeholder(self, text: str):
        # these are the maximum lengths we've decided these strings should be
        text = text.replace("<pc_hiryu>", "<&13_aaaaaaa>")
        text = text.replace("<cs_pchero_hiryu>", "<&13_aaaaaab>")
        text = text.replace("<cs_pchero_race>", "<&8_aaa>")
        text = text.replace("<cs_pchero>", "<13_aaaaaac>")
        text = text.replace("<kyodai_rel1>", "<&7_aa>")
        text = text.replace("<kyodai_rel2>", "<&7_ab>")
        text = text.replace("<kyodai_rel3>", "<&7_ac>")
        text = text.replace("<pc_hometown>", "<&8_aab>")
        text = text.replace("<pc_race>", "<&8_aac>")
        text = text.replace("<pc_rel1>", "<&7_ad>")
        text = text.replace("<pc_rel2>", "<&7_ae>")
        text = text.replace("<pc_rel3>", "<&7_af")
        text = text.replace("<kyodai>", "<&13_aaaaaac>")
        text = text.replace("<pc>", "<&13_aaaaaad>")
        text = text.replace("<client_pcname>", "<&13_aaaaaae>")
        text = text.replace("<heart>", "<&2a>")
        text = text.replace("<diamond>", "<&2b>")
        text = text.replace("<spade>", "<&2c>")
        text = text.replace("<clover>", "<&2d>")
        text = text.replace("<r_triangle>", "<&2e>")
        text = text.replace("<l_triangle>", "<&2f>")
        text = text.replace("<half_star>", "<&2g>")
        text = text.replace("<null_star>", "<&2h>")
        text = text.replace("<npc>", "<&13_aaaaaaf>")
        text = text.replace("<pc_syokugyo>", "<&13_aaaaaag>")
        text = text.replace("<pc_original>", "<&13_aaaaaah>")
        text = text.replace("<log_pc>", "<&13_aaaaaai>")
        text = text.replace("<1st_title>", "<&20_aaaaaaaaaaaaaa>")
        text = text.replace("<2nd_title>", "<&20_aaaaaaaaaaaaab>")
        text = text.replace("<3rd_title>", "<&20_aaaaaaaaaaaaac>")
        text = text.replace("<4th_title>", "<&20_aaaaaaaaaaaaad>")
        text = text.replace("<5th_title>", "<&20_aaaaaaaaaaaaae>")
        text = text.replace("<6th_title>", "<&20_aaaaaaaaaaaaaf>")
        text = text.replace("<7th_title>", "<&20_aaaaaaaaaaaaag>")

        # fmt: off
        # remove strings we dont want to evaluate
        text = text.replace("<attr>", "")
        text = text.replace("<auto_br=1500>", "")
        text = text.replace("<auto_br=20000>", "")
        text = text.replace("<auto_br=2000>", "")
        text = text.replace("<auto_br=2500>", "")
        text = text.replace("<auto_br=4000>", "")
        text = text.replace("<auto_br=5000>", "")
        text = text.replace("<auto_bw=10000>", "")
        text = text.replace("<auto_bw=1000>", "")
        text = text.replace("<auto_bw=1500>", "")
        text = text.replace("<auto_bw=1700>", "")
        text = text.replace("<auto_bw=2000>", "")
        text = text.replace("<auto_bw=2500>", "")
        text = text.replace("<auto_bw=3000>", "")
        text = text.replace("<auto_bw=3500>", "")
        text = text.replace("<auto_bw=4000>", "")
        text = text.replace("<auto_bw=5000>", "")
        text = text.replace("<auto_bw=60000>", "")
        text = text.replace("<auto_bw=800>", "")
        text = text.replace("<auto_bw_break=3000>", "")
        text = text.replace("<br>", "")
        text = text.replace("<br_break>", "")
        text = text.replace("<break>", "")
        text = text.replace("<bw>", "")
        text = text.replace("<bw_break>", "")
        text = text.replace("<bw_clear>", "")
        text = text.replace("<bw_hide>", "")
        text = text.replace("<cancel>", "")
        text = text.replace("<case 1>", "")
        text = text.replace("<case 2>", "")
        text = text.replace("<case 3>", "")
        text = text.replace("<case 4>", "")
        text = text.replace("<case 5>", "")
        text = text.replace("<case_cancel>", "")
        text = text.replace("<case_end>", "")
        text = text.replace("<close>", "")
        text = text.replace("<close_irai>", "")
        text = text.replace("<color_gray>", "")
        text = text.replace("<color_white>", "")
        text = text.replace("<color_yellow>", "")
        text = text.replace("<else>", "")
        text = text.replace("<end>", "")
        text = text.replace("<end_attr>", "")
        text = text.replace("<endif>", "")
        text = text.replace("<feel_angry_lv2>", "")
        text = text.replace("<feel_angry_lv3>", "")
        text = text.replace("<feel_happy_lv1>", "")
        text = text.replace("<feel_happy_lv2>", "")
        text = text.replace("<feel_happy_lv3>", "")
        text = text.replace("<feel_sad_lv1>", "")
        text = text.replace("<feel_sad_lv3>", "")
        text = text.replace("<feel_think_lv3>", "")
        text = text.replace("<icon_exc>", "")
        text = text.replace("<if_woman>", "")
        text = text.replace("<LEFT>", "")
        text = text.replace("<left>", "")
        text = text.replace("<me 57>", "")
        text = text.replace("<me 60>", "")
        text = text.replace("<me 61>", "")
        text = text.replace("<me 62>", "")
        text = text.replace("<me 64>", "")
        text = text.replace("<me 71>", "")
        text = text.replace("<me 72>", "")
        text = text.replace("<me 73>", "")
        text = text.replace("<me 74>", "")
        text = text.replace("<me 75>", "")
        text = text.replace("<me_57>", "")
        text = text.replace("<me_58>", "")
        text = text.replace("<me_60>", "")
        text = text.replace("<me_61>", "")
        text = text.replace("<me_62>", "")
        text = text.replace("<me_70>", "")
        text = text.replace("<me_71>", "")
        text = text.replace("<me_72>", "")
        text = text.replace("<me_73>", "")
        text = text.replace("<me_nots 69>", "")
        text = text.replace("<open_irai>", "")
        text = text.replace("<pipipi_default>", "")
        text = text.replace("<pipipi_high>", "")
        text = text.replace("<pipipi_low>", "")
        text = text.replace("<pipipi_mid>", "")
        text = text.replace("<pipipi_npc 10670>", "")
        text = text.replace("<pipipi_off>", "")
        text = text.replace("<pipipi_on>", "")
        text = text.replace("<pipipi_shigh>", "")
        text = text.replace("<right>", "")
        text = text.replace("<%sB_renkin1><%sB_kakko><%sB_plusminus><%sB_renkindiff><%sB_kokka>", "")
        text = text.replace("<%sB_renkin1>.<%sB_renkin2><%sB_kakko><%sB_plusminus><%sB_renkindiff1><%sB_decimalpoint><%sB_renkindiff2><%sB_kokka>", "")
        text = text.replace("<se Joutyu_SE 121>", "")
        text = text.replace("<se Joutyu_SE 24>", "")
        text = text.replace("<se Joutyu_SE 40>", "")
        text = text.replace("<se Joutyu_SE 57>", "")
        text = text.replace("<se System 18>", "")
        text = text.replace("<se System 7>", "")
        text = text.replace("<se_nots Joutyu_SE 10>", "")
        text = text.replace("<se_nots Joutyu_SE 122>", "")
        text = text.replace("<se_nots Joutyu_SE 138>", "")
        text = text.replace("<se_nots Joutyu_SE 150>", "")
        text = text.replace("<se_nots Joutyu_SE 24>", "")
        text = text.replace("<se_nots Joutyu_SE 28>", "")
        text = text.replace("<se_nots Joutyu_SE 35>", "")
        text = text.replace("<se_nots Joutyu_SE 37>", "")
        text = text.replace("<se_nots Joutyu_SE 38>", "")
        text = text.replace("<se_nots Joutyu_SE 39>", "")
        text = text.replace("<se_nots Joutyu_SE 40>", "")
        text = text.replace("<se_nots Joutyu_SE 42>", "")
        text = text.replace("<se_nots Joutyu_SE 47>", "")
        text = text.replace("<se_nots Joutyu_SE 57>", "")
        text = text.replace("<se_nots Joutyu_SE 80>", "")
        text = text.replace("<se_nots Joutyu_SE 89>", "")
        text = text.replace("<se_nots System 0>", "")
        text = text.replace("<se_nots System 10>", "")
        text = text.replace("<se_nots System 17>", "")
        text = text.replace("<se_nots System 18>", "")
        text = text.replace("<se_nots System 1>", "")
        text = text.replace("<se_nots System 20>", "")
        text = text.replace("<se_nots System 2>", "")
        text = text.replace("<se_nots System 35>", "")
        text = text.replace("<se_nots System 3>", "")
        text = text.replace("<se_nots System 4>", "")
        text = text.replace("<se_nots System 5>", "")
        text = text.replace("<se_nots System 6>", "")
        text = text.replace("<se_nots System 7>", "")
        text = text.replace("<se_nots System 8>", "")
        text = text.replace("<se_nots System 9>", "")
        text = text.replace("<select 2>", "")
        text = text.replace("<select>", "")
        text = text.replace("<select_end>", "")
        text = text.replace("<select_nc>", "")
        text = text.replace("<select_nc_se_off>", "")
        text = text.replace("<select_se_off 2>", "")
        text = text.replace("<select_se_off 3>", "")
        text = text.replace("<select_se_off 4>", "")
        text = text.replace("<select_se_off 5>", "")
        text = text.replace("<select_se_off 6>", "")
        text = text.replace("<select_se_off>", "")
        text = text.replace("<shake_big>", "")
        text = text.replace("<speed=0>", "")
        text = text.replace("<speed=20>", "")
        text = text.replace("<speed=30>", "")
        text = text.replace("<sys_msg_wait>", "")
        text = text.replace("<turn end>", "")
        text = text.replace("<turn_end>", "")
        text = text.replace("<wait 500>", "")
        text = text.replace("<wait=1000>", "")
        text = text.replace("<wait=100>", "")
        text = text.replace("<wait=1300>", "")
        text = text.replace("<wait=1500>", "")
        text = text.replace("<wait=2000>", "")
        text = text.replace("<wait=200>", "")
        text = text.replace("<wait=400>", "")
        text = text.replace("<wait=800>", "")
        text = text.replace("<wait=850>", "")
        text = text.replace("<yesno 1>", "")
        text = text.replace("<yesno 2>", "")
        text = text.replace("<yesno 3>", "")
        text = text.replace("<yesno2>", "")
        text = text.replace("<yesno>", "")
        text = text.replace("<yesno_2>", "")
        text = text.replace("<yesno_nc 2>", "")
        text = text.replace("<yesno_nc>", "")
        text = text.replace("<yesno_se_off>", "")
        # fmt: on

        return text

    def check_single(self, source, target, unit):
        lines = target.split('\n')
        for line in lines:
            line = self.replace_with_placeholder(text=line)
            encoded_line = line.encode('utf-8')
            if len(encoded_line) > 46:
                return True
